void serial1_begin(uint32_t divisor);
void serial1_format(uint32_t format);
void serial1_end(void);
void serial1_set_transmit_pin(uint8_t pin);
void serial1_putchar(uint32_t c);
void serial1_write(const void *buf, unsigned int count);
void serial1_write(const void *buf, unsigned int count);
void serial1_flush(void);
int serial1_write_buffer_free(void);
int serial1_available(void);
int serial1_getchar(void);
int serial1_peek(void);
void serial1_clear(void);
void uart1_status_isr(void);
